<a href="https://colab.research.google.com/github/Tagore-7/Pytorch_Tutorial/blob/main/pytorch_1_intro_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
#lists
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [4]:
my_list = [[1,2,3,4,5],[1,2,3,4,5]]
my_list

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

In [5]:
#numpy array
np1 = np.random.rand(3,4)
np1

array([[0.91095217, 0.84671742, 0.99755848, 0.67503597],
       [0.30996147, 0.39944686, 0.97913427, 0.8187464 ],
       [0.84157185, 0.01908262, 0.88506157, 0.08593581]])

In [6]:
np1.dtype

dtype('float64')

In [8]:
#tensor
tensor_1 = torch.rand(3,4)
tensor_1

tensor([[0.4274, 0.8359, 0.9919, 0.7210],
        [0.1488, 0.3248, 0.0035, 0.7246],
        [0.7627, 0.1238, 0.9739, 0.8284]])

In [9]:
tensor_1.dtype

torch.float32

In [10]:
tensor_3d = torch.ones(2,3,4)
tensor_3d

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
#create a tensor out of numpy
tensor_np = torch.tensor(np1)
tensor_np

tensor([[0.9110, 0.8467, 0.9976, 0.6750],
        [0.3100, 0.3994, 0.9791, 0.8187],
        [0.8416, 0.0191, 0.8851, 0.0859]], dtype=torch.float64)

In [13]:
# tensor operations
tensor_2 = torch.arange(10)
tensor_2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# reshape and view
tensor_reshape = tensor_2.reshape(2,5)
tensor_reshape

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
  # reshape if we don't know the number of the items using -1
  tensor_3 =  torch.arange(10)
  tensor_3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
tensor_reshape_unknown = tensor_3.reshape(2,-1)
tensor_reshape_unknown


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
# make sure the what output you want you can also do in reverse
tensor_reshape_unknown = tensor_3.reshape(-1,2)
tensor_reshape_unknown


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [20]:
# reshape vs view
tensor_4 = torch.arange(10)
tensor_4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
torch_view = tensor_4.view(2,-1)
torch_view

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [22]:
# with reshape and view they will update
tensor_5 = torch.arange(10)
tensor_5


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
tensor_6 = tensor_5.reshape(-1,5)
tensor_6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
tensor_5[2] = 7
tensor_5

tensor([0, 1, 7, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# change will reflect in other tensor too
tensor_6

tensor([[0, 1, 7, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
# Slices
tensor_7 = torch.arange(10)
tensor_7


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# grab an item
tensor_7[5]

tensor(5)

In [30]:
# Grab a slice
tensor_8 = tensor_7.reshape(5,2)
tensor_8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [31]:
tensor_8[:,1] #looks like list

tensor([1, 3, 5, 7, 9])

In [32]:
# return a column
tensor_8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])