<a href="https://colab.research.google.com/github/Tagore-7/Pytorch_Tutorial/blob/main/pytorch_2_math_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [25]:
# Math operations
tensor_1 = torch.tensor([1,2,3,4])
tensor_2 = torch.tensor([1,2,3,4])

In [4]:
# Addition
tensor_add = tensor_1 + tensor_2
tensor_add

tensor([2, 4, 6, 8])

In [6]:
# Addition longhand
tensor_add = torch.add(tensor_1, tensor_2)
tensor_add

tensor([2, 4, 6, 8])

In [7]:
# subtraction
tensor_sub = tensor_1 - tensor_2
tensor_sub

tensor([0, 0, 0, 0])

In [8]:
torch.sub(tensor_1, tensor_2)

tensor([0, 0, 0, 0])

In [10]:
# multiplication
tensor_1 * tensor_2

tensor([ 1,  4,  9, 16])

In [11]:
torch.mul(tensor_1, tensor_2)

tensor([ 1,  4,  9, 16])

In [12]:
# division
tensor_1 / tensor_2

tensor([1., 1., 1., 1.])

In [13]:
torch.div(tensor_1, tensor_2)

tensor([1., 1., 1., 1.])

In [14]:
# remainders
tensor_1 % tensor_2

tensor([0, 0, 0, 0])

In [15]:
torch.remainder(tensor_1, tensor_2)

tensor([0, 0, 0, 0])

In [16]:
# exponents or power
tensor_1 ** tensor_2

tensor([  1,   4,  27, 256])

In [17]:
torch.pow(tensor_1, tensor_2)

tensor([  1,   4,  27, 256])

In [18]:
# another ways to add
tensor_1.add(tensor_2)

tensor([2, 4, 6, 8])

In [24]:
# reassigment
tensor_1 = torch.tensor([1,2,3,4])
tensor_2 = torch.tensor([1,2,3,4])
tensor_1 = tensor_1 + tensor_2
tensor_1

tensor([2, 4, 6, 8])

In [26]:
# another way
tensor_1 = torch.tensor([1,2,3,4])
tensor_2 = torch.tensor([1,2,3,4])
tensor_1.add_(tensor_2)

tensor([2, 4, 6, 8])